### PR TITLE
added support for hashing-passwords filling

### PR DESCRIPTION
**Pull request by streetsamurai00mi**
I think it would be better to store hashing-password. Keeping raw passwords in the settings file can lead to leaking credentials.
Do you think that could be merged? Should I do something more?

### CODE REVIEW

**Comment by yarrm80s** [comment]
@streetsamurai00mi nope that's intentionally not supported

**Comment by yarrm80s** [comment]
I will not be adding any features that are only useful for piracy, and this is easily one of the biggest ones

**Comment by yarrm80s** [comment]
anyways the better way to avoid passwords leaking is for me to finish the advanced sessions mode of Orpheus itself, but for now the simple system where all the login details are just added into the config file is extremely convenient for testing so that's a very low priority change

**Comment by Dniel97** [comment]
The password needs to be stored in a raw format because pretty much Qobuz is the only service which hashes the passwords before sending to the server/API. Any other service just uses the raw password over https anyway and hashing is a one way function, so I would break all other modules just like @yarrm80s said.

**Comment by streetsamurai00mi** [comment]
> I will not be adding any features that are only useful for piracy, and this is easily one of the biggest ones
> all the login details are just added into the config file is extremely convenient for testing
Absolutely. It's a clear ideology, I see what you mean
> so I would break all other modules just like @yarrm80s said.
I made a serious mistake, that line should used something like `*{v for k,v in settings.items() if k=='password_hash'}`
Anyways, the performance gains almost 0 so it's better to keep orpheusdl untouched. I should probably just work with some modules on the local repository

**Comment by yarrm80s** [comment]
thanks anyways for the pull request, but yeah sorry hashed password input is not something I would support, just because it's abused in other projects for pirates who use shared accounts that come with hashed passwords that aren't able to be changed easily

**Pull request closed without merging**
